### PR TITLE
fix(user-auth): add sort to getAllJournal query

### PR DESCRIPTION
**Pull request by khanjasir90**
## #71
Signed-off-by: khanjasir90 <khanmohdjasir@gmail.com>
Description: Added sort function to getAllJournals query to return the most recent journal first

### CODE REVIEW

**Comment by khanjasir90** [comment]
@d-e-v-esh could u pls review!

**Comment by khanjasir90** [comment]
@d-e-v-esh could u review this in ur free time :)

**Comment by khanjasir90** [comment]
https://www.loom.com/share/7d1e9500ade44f65bf66dd182644e3c8

**Comment by d-e-v-esh** [comment]
@khanjasir90 This works well. BTW, we are following the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) to write the commit messages. That will help us in versioning later. The commit message for this feature can be something like `fix(user-auth): add sort to getAllJournal query`. I'll merge after you change the commit message 👍

**Comment by khanjasir90** [comment]
@d-e-v-esh commit msg updated!

**Comment by d-e-v-esh** [comment]
@khanjasir90 It hasn't updated yet.
image

**Comment by khanjasir90** [comment]
@d-e-v-esh could u pls cross check now!

**Review by d-e-v-esh — APPROVED** [review]
LGTM!

**Pull request merged**
