### PR TITLE
Added new ChangeFullName resolver

### PR DESCRIPTION
**Pull request by hazardemircan**
- Added ChangeFullName resolver with auth

### CODE REVIEW

**Comment by d-e-v-esh** [comment]
@hazardemircan Can you please remove the 14 day older commit that we don't need anymore? Otherwise it might get little confusing later. If you need any help doing that then let me know 👍

Also try to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) while writing the commit messages. That will help us in versioning later. The commit message for this feature can be something like `feat(user-auth): add changeFullName Mutation` ([past tense in not preferred in commit messages](https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages), you can use whatever you want in the commit description).

**Comment by d-e-v-esh** [comment]
If you need any help for anything else, let me know 👍

**Comment by hazardemircan** [comment]
I couldn't remove old commit can i create new branch from my latest commit and PR with it?

> @hazardemircan Can you please remove the 14 day older commit that we don't need anymore? Otherwise it might get little confusing later. If you need any help doing that then let me know 👍
> 
> Also try to follow [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/) while writing the commit messages. That will help us in versioning later. The commit message for this feature can be something like `feat(user-auth): add changeFullName Mutation` ([past tense in not preferred in commit messages](https://stackoverflow.com/questions/3580013/should-i-use-past-or-present-tense-in-git-commit-messages), you can use whatever you want in the commit description).

**Comment by d-e-v-esh** [comment]
@hazardemircan Sorry for the delay, I didn't see your reply.

> can i create new branch from my latest commit and PR with it?

Yes, that would be amazing 👍

**Comment by d-e-v-esh** [comment]
@hazardemircan Hey👋 I just wanted to ask if you are still working on it. If not then I would like to give it to someone else who would like to work on this problem. Let me know👍

**Comment by d-e-v-esh** [comment]
Closed this PR as there are no updates.

**Pull request closed without merging**
