### PR TITLE
Create PULL_REQUEST_TEMPLATE.md

### PR DESCRIPTION
**Pull request by CIPHERTron**
Added a Pull Request Template. I haven't mentioned testing because as of now, we don't have the project setup ready. So, once we have a minimal flask setup, I'll add pytest checkboxes asking if the tests has passed or not!

Now, the PR template looks like this:
image

### CODE REVIEW

**Comment by CIPHERTron** [comment]
@JPTIZ could you please review the PR and suggest if any changes required?

**Comment by yochannah** [comment]
Hey @CIPHERTron - the first half of this is great, but we don't really have warnings or code standards yet. What would you suggest?

**Comment by CIPHERTron** [comment]
Hola @yochannah 
Apologies for the late reply, got caught up with some work recently. 

So, yeah we can discard the second half as of now. But, we'll be needing a contributing guideline and code of conduct soon. It's kind of important for a project. And about testing and linting, once the project structure is finalized and a minimal app is set up in the repo(which I think will be done soon), then we can add the checkbox for tests and linter warnings if any!

At that time, we'll add the Contributing guidelines, code standards, and other stuffs which is mentioned in the second half. How does that sound?

**Comment by CIPHERTron** [comment]
We will think about this afterwards. Let's get the server up and running first 🚀
For now, I'm closing this PR.

**Pull request closed without merging**
