### PR TITLE
chore: Setup Deploy Settings to Heroku

### PR DESCRIPTION
**Pull request by CIPHERTron**

### CODE REVIEW

**Comment by JPTIZ** [comment]
Ok, we've got conflicts after merging #19.
About `requirements.txt`: do we need it versioned? I think I remember we getting it to work without it after fixing some things with specifying Python versions and updating `poetry.lock` (https://github.com/codeisscience/journal-policy-tracker-backend/pull/20/commits/0a7f3f1ca70c3cdc6470d3188400622266526261).

**Comment by CIPHERTron** [comment]
> Ok, we've got conflicts after merging #19.
> About `requirements.txt`: do we need it versioned? I think I remember we getting it to work without it after fixing some things with specifying Python versions and updating `poetry.lock` ([0a7f3f1](https://github.com/codeisscience/journal-policy-tracker-backend/commit/0a7f3f1ca70c3cdc6470d3188400622266526261)).

Yes @JPTIZ . Actually, there wasn't any need of exporting the requirements.txt. Our work was done by changing the heroku configs. I'll delete it and commit the changes here only.

**Comment by JPTIZ** [comment]
> > Ok, we've got conflicts after merging #19.
> > About `requirements.txt`: do we need it versioned? I think I remember we getting it to work without it after fixing some things with specifying Python versions and updating `poetry.lock` ([0a7f3f1](https://github.com/codeisscience/journal-policy-tracker-backend/commit/0a7f3f1ca70c3cdc6470d3188400622266526261)).
> 
> Yes @JPTIZ . Actually, there wasn't any need of exporting the requirements.txt. Our work was done by changing the heroku configs. I'll delete it and commit the changes here only.

Sure, looks a good idea then ):

**Comment by CIPHERTron** [comment]
@JPTIZ I've resolved the conflicts and deleted the `reuirements.txt`. Now, the PR is good to go!

**Comment by CIPHERTron** [comment]
> @JPTIZ I've resolved the conflicts and deleted the `reuirements.txt`. Now, the PR is good to go!

After you merge this PR, I'll resolve the conflicts in the next PR 😂😂

**Review by JPTIZ — APPROVED** [review]

**Pull request merged**
